### ISSUE TITLE
iplboot2

### ISSUE THREAD

**Issue by gnadenlos** [redolution/iplboot#1]
Could you make an iplboot2 that looks for ipl2.dol on the SD card? 

That would be useful to boot different apps from SD card on Qoob Pro without the need for a disc.

**Comment by Streetwalrus** [comment]
Swiss supports more advanced chainloading, I suggest you use that as your ipl.dol The point of iplboot is to be as simple as possible.

**Comment by gnadenlos** [comment]
My idea is not about chainloading. It's about loading two different dols from the Qoob Pro application menu. The main iplboot doesn't have to change. 

I was thinking about providing a completely separate gcb file that would load ipl2.dol instead of ipl.dol. So we could load Swiss (ipl.dol) and GBI (ipl2.dol) directly from Qoob Pro. That's faster than loading Swiss first, if we want to play GB/GBA games.

**Comment by Streetwalrus** [comment]
Separate GCB is not feasible, you wouldn't be able to choose which one to boot. You would have to use the DOL together with the Qoob menu.
It could also be implemented by testing for a particular button on the controller, but I'm sure if I want that in iplboot itself.

**Comment by gnadenlos** [comment]
I've installed the official Qoob BIOS (in block 1+2 of the memory) and iplboot.gcb (block 3). That way iplboot shows up in the application menu. If there was an iplboot2.qcb I could add that too and could select both variants in the application menu. Doesn't have to be in dol format, qcb format works better from my experience.

**Comment by Streetwalrus** [comment]
I'm surprised the GCB works at all that way. I think I'm going to add the button thing.

**Comment by gnadenlos** [comment]
If you add the button thing maybe you could add a second button to start the unmodified Gamecube GUI/BIOS, so we could boot games without removing the SD Gecko or SD card.

**Comment by Streetwalrus** [comment]
I took a look. libogc's controller driver is very unreliable and I don't feel like debugging things. Maybe some other day.

**Comment by 9ary** [comment]
As of #7 this has been implemented.
