### ISSUE TITLE
iplboot not loading correctly from slot-A

### ISSUE THREAD

**Issue by GizmoTheGreen** [redolution/iplboot#2]
Hi, while troubleshooting loading iso from SD card with swiss I realized I can't boot from slot-A.
Screenshot attached.

moving the homemade sd-gecko to slotB boots every time. 
this is the latest iplboot r5.2 booting straight off of Viper GC Extreme as firmware/vgc. (as cbp plugin didn't even load)
![image](https://user-images.githubusercontent.com/1146558/45258444-cd53ac00-b3b7-11e8-8ac3-cac04e4a55c4.png)

**Comment by Streetwalrus** [comment]
I can reproduce this with my Qoob Pro setup so that's worth looking into. I'll check it out tomorrow.
Side note: unless Cobra accepts DOLs as "plugins", it is expected that it won't work. The VGC file is a Viper BIOS and won't work any other way.

**Comment by GizmoTheGreen** [comment]
ah ofcourse, for cobra plugin I used the tool to convert the .dol to .cbp, then attached it to the cobra 2.1 vgc as such
`copy /b cobra21.vgc+iplboot.cbp cobrawithiplboot.vgc`
then flashed that, which gives me iplboot as an option in the menu. but it just "loading dol" forever.

right now I'm running the plain VGC flashed as is to the viper, no viper OS. only swiss from SD.
but swiss won't load games from slotB for me, only A, so as it is now I have to keep moving my adapter around.

**Comment by Streetwalrus** [comment]
Yeah I've seen your thread on GCF. I'll try to fix booting from slot A tomorrow. Shouldn't be hard but I hope I won't break something else again.

**Comment by 9ary** [comment]
Extrems has updated the codebase a little so hopefully this should be resolved now. I'm going to close this, please reopen if it still doesn't work in the next release.
