### ISSUE TITLE
cant compile: ogc/disc_io.h: No such file or directory

### ISSUE THREAD

**Issue by kjuno** [redolution/iplboot#22]
Error:
/iplboot/source/ffshim.h:4:10: fatal error: ogc/disc_io.h: No such file or directory
![Unbenannt](https://user-images.githubusercontent.com/34090514/182959342-e6a75791-e8bf-4f6d-b230-9dd674b30d9f.PNG)

- devkitpro correctly installed
- libogc2 installed and compiled
- paths set 
![path](https://user-images.githubusercontent.com/34090514/182959339-686b3e0a-e6f7-4909-8b34-14afe34bd826.PNG)

i dont know what to do

**Comment by 9ary** [comment]
Seems to me like libogc2 might be installed incorrectly. Does C:/devkitPro/libogc2 exist? What's in there?

**Comment by kjuno** [comment]
![Unbenannt](https://user-images.githubusercontent.com/34090514/182960441-3795cf1e-4526-4a57-95be-f1b3b8dfd120.PNG)

**Comment by 9ary** [comment]
You're not supposed to download the libogc2 repo there. You need to clone it outside of the devkitPro installation directory, and run `make install`.

**Comment by kjuno** [comment]
oh my bad, but where should i know about that?

**Comment by kjuno** [comment]
on the libogc2 repo there are no instructions

**Comment by 9ary** [comment]
This isn't properly documented unfortunately, but it's a very common way of compiling and installing software from source. Documentation should be added to libogc2 and upstream libogc, not here.

**Comment by kjuno** [comment]
good to know, I am very new to this open source community, sorry for disturbing you

**Comment by 9ary** [comment]
Not at all, you're welcome to ask any questions you might have.
