### ISSUE TITLE
error compile

### ISSUE THREAD

**Issue by ledu205** [redolution/iplboot#4]
I trying to compile minimal ipl boot for support SD2SP2,but i have error when compile

ffshim.c
make[1]: powerpc-eabi-clang: Command not found
make[1]: *** [/opt/devkitpro/devkitPPC/base_rules:18: ffshim.o] Error 127
make: *** [Makefile:111: build] Error 2

i think problem with clang but i'm nweebie i compilation, i hope you could help me

**Comment by Streetwalrus** [comment]
Did you even read the readme?

**Comment by ledu205** [comment]
yes but don't understand this line "Clang (ln -s /usb/bin/clang $DEVKITPPC/bin/powerpc-eabi-clang)"

**Comment by Streetwalrus** [comment]
Make sure clang is installed, then `sudo ln -s /usb/bin/clang /opt/devkitpro/devkitPPC/bin/powerpc-eabi-clang`.

**Comment by ledu205** [comment]
i have install this "http://releases.llvm.org/9.0.0/LLVM-9.0.0-win64.exe" i use windows 10

**Comment by Streetwalrus** [comment]
You need to install clang through msys. That's all I can tell you, I don't use windows.

**Comment by ledu205** [comment]
ok i test and if I can't do it i install a linux for complie

**Comment by ledu205** [comment]
same error with ubuntu
make
ssaram.c
make[1]: powerpc-eabi-clang: Command not found
make[1]: *** [/opt/devkitpro/devkitPPC/base_rules:18: ssaram.o] Error 127
make: *** [Makefile:111: build] Error 2

and this command
sudo ln -s /usb/bin/clang /opt/devkitpro/devkitPPC/bin/powerpc-eabi-clang
ln: impossible de créer le lien symbolique '/opt/devkitpro/devkitPPC/bin/powerpc-eabi-clang': Le fichier existe

**Comment by ledu205** [comment]
I have install ubuntu and compile bur new error
ssaram.c
main.c
sidestep.c
ffshim.c
ffsystem.c
ff.c
ffunicode.c
linking ... iplboot-master.elf
output ... iplboot-master.dol
pack IPL ... iplboot-master.gcb
Traceback (most recent call last):
  File "./dol2ipl.py", line 161, in <module>
    sys.exit(main())
  File "./dol2ipl.py", line 83, in main
    with open(sys.argv[1], "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'ipl.rom'
make[1]: *** [/home/gc/Téléchargements/iplboot-master/Makefile:139: /home/gc/Téléchargements/iplboot-master/iplboot-master.gcb] Error 1
make: *** [Makefile:111: build] Error 2

**Comment by Streetwalrus** [comment]
You need a dump of the original IPL. You can use Swiss to dump yours. Rename it to ipl.rom and put it in the iplboot folder. You will also get an error while packing the Qoob SX version, simply remove the `$(OUTPUT_SX).dol` from line 133 in the Makefile. Finally note that it won't fit in a non-extreme Viper GC anymore either.

**Comment by ledu205** [comment]
indeed i miss ipl.rom i test with that
