### ISSUE TITLE
qoob sx r9 dont work 

### ISSUE THREAD

**Issue by AceCuba** [redolution/iplboot#45]
for a wile im using a qoob sx on my cube , use a swiss disk and  xeno to make the qoob on flash mode think im booting the oficial app , when im in swiss i can flash no issue r5 r8 .dol versions of the fw , but if i flash the r9 , the qoob sx says done but boots to the recovery screen and says loading the flashed app and stuck there , r5 r8 beta work just fine

**Comment by 9ary** [comment]
Thank you for reporting!

I was looking for someone who can test, since I don't have a Qoob SX myself and it's by far the weirdest modchip, I wonder what's going wrong here...

**Comment by 9ary** [comment]
@AceCuba can you try #46 and see if it helps?

**Comment by AceCuba** [comment]
on it , if you need a tester for qoob sx i can help , gt the cube ready for flashing the .dol , let my test the .elf you upload . nop same thing the .elf says the update is done , i reboot and i get to the recovery menu saing starting flashed app . the r8 .dol works without issues
![photo_2024-01-02_20-34-18](https://github.com/redolution/iplboot/assets/59297390/2270e0bf-b207-4400-a38f-7ee36aeabfa6)

**Comment by AceCuba** [comment]
sorry for the late reply and happy new year

**Comment by AceCuba** [comment]
ok lets see , the qoobsx is working fine with the r8 im going to dump that one , and update the qoob to r9 and dump that one to , let  my get home from work i will see

**Comment by AceCuba** [comment]
why unpluging the qoob is necesary

**Comment by 9ary** [comment]
It doesn't really matter which one you dump, I'm interested in the "recovery" section of flash.

Unplugging the modchip is necessary to reset it, because it has to disable itself after boot.

**Comment by AceCuba** [comment]
okps then i will follow  your instructions when i get back home

**Comment by AceCuba** [comment]
can i just dump the r8 i got install and spare me the update and rollback from r9

**Comment by 9ary** [comment]
Yes, that's fine.

**Comment by AceCuba** [comment]
hey my internet was out , tomorrow i will dump the file and upload here thanks

**Comment by 9ary** [comment]
No problem, take your time.

**Comment by AceCuba** [comment]
hope this work sorry for thetime , work this month have bean intenss . this is qoob sx running r8 with no issue
[ipl.zip](https://github.com/redolution/iplboot/files/14072275/ipl.zip)

**Comment by 9ary** [comment]
Unfortunately this is a regular NTSC 1.1 dump. Are you sure you followed the instructions correctly?

**Comment by AceCuba** [comment]
yeap i still got the cube a part so , what can i do

**Comment by 9ary** [comment]
I don't know. I'm away from home until at least mid February, and at this point I'm out of ideas anyway. I think I'll need the real thing in order to progress.

**Comment by 9ary** [comment]
I now have a Qoob SX in my possession thanks to @webhdx. I'm still away from home for the next month, but I'm able to test and dump it myself now.

Thanks for your patience.

**Comment by 9ary** [comment]
It was a dumb issue. Fixed in r9.1!
